### ISSUE TITLE
Soul Press doesnt create soul sand

### ISSUE THREAD

**Issue by CyprusGrunumn** [BTW-Community/BWR#1]
-FC added a new dung block to replace the old, therefore anything referencing the old Dung block will be broken
		- Soul Press (Dragon Orbs dont combine, and the dung doesnt become soulsand) 
		(seems like this is caused by using the old Dung Block.

**Comment by Warr1024** [comment]
![image](https://user-images.githubusercontent.com/324806/133911717-74ef2f68-5240-4150-85fd-3c55a198d68f.png)

**Comment by CyprusGrunumn** [comment]
Only works if the save is closed and opened again, the xp orb isnt being saved.

This is an upstream issue that will be fixed by dawn and Zhil
